# Demo config file 
# You can follow this template to create your own config file
# Refer to the config files in the configs/ directory to see all the available options
  
checkpointing:
  run_name: "pico-maml-demo-3"
  save_checkpoint_repo_id: "davidafrica/pico-maml"

  learning_dynamics:
    batch_size: 16

model:
    d_model: 24
    activation_hidden_dim: 96

training:
  optimization:
    lr: 0.001
    lr_warmup_steps: 30

    gradient_accumulation_steps: 4


  fabric:
    num_nodes: 1
    num_devices: 4
  
evaluation:
  metrics:
    - paloma
  paloma:
    batch_size: 32

monitoring:
  logging:
    log_every_n_steps: 10

smlmt:
  enabled: true
  probability: 0.2        # probability that the meta–learning component is computed on any given iteration
  num_classes: 3           # K: number of target words per task e.g [2, 5, 10]
  support_per_class: 10    # S: number of support sentences per class e.g [5, 10, 20]
  query_per_class: 5       # Q: number of query sentences per class
  smlmt_weight: 1  # weight to scale the meta–learning loss relative to the supervised loss
  inner_lr: 1e-3
  inner_steps: 10 # e.g [20, 50, 100]