# runpod-pico-maml-decoder-medium.yaml

checkpointing:
  run_name: "pico-maml-decoder-medium-1"
  save_to_hf: true         # no pushes to HuggingFace
  auto_resume: true        # don’t try to resume from disk
  save_every_n_steps: 100 
  hf_checkpoint:
    repo_id: "davidafrica/pico-maml-decoder-medium"

  learning_dynamics:
    batch_size: 128

model:
    d_model: 768
    activation_hidden_dim: 3072

monitoring:
  save_to_wandb: true      
  logging:
    log_every_n_steps: 10 

training:
  max_steps: 10000000
  optimization:
    gradient_accumulation_steps: 8
    gradient_checkpointing: true

  fabric:
    precision: "bf16-mixed"
    devices: 4              # use 4 GPUs on this node
    num_nodes: 1

smlmt:
  enabled: true
  hybrid_ratio: 0.5
  inner_steps: 10
  inner_lr: 0.01
  classifier_head:
    num_layers: 4
    hidden_dim: 128
    dropout: 0.1
    init_method: "xavier"
  k_shot: 4
  n_way: 32

evaluation:
  paloma:
    batch_size: 16
